[workspace]
resolver = "3"
members = ["synapse", "locator", "proxy", "ingest-router"]
default-members = ["synapse"]

[workspace.dependencies]
metrics = "0.24.2"
metrics-exporter-statsd = "0.9.0"
sentry = "0.45.0"
serde = { version = "1.0.219", features = ["derive"] }
tempfile = "3"
thiserror = "2.0.16"
tokio = { version = "1.46.1", features = ["full"] }
url = "2.5"
