[workspace]
resolver = "3"
members = ["synapse", "locator", "proxy", "ingest-router", "shared/routing"]
default-members = ["synapse"]

[workspace.dependencies]
serde = { version = "1.0.219", features = ["derive"] }
tempfile = "3"
thiserror = "2.0.16"
tokio = { version = "1.46.1", features = ["full"] }
url = "2.5"
