locator:
  control_plane:
    url: "http://127.0.0.1:9000"
  backup_route_store:
    type: filesystem
    base_dir: target/cache
    filename: backup.bin
    # none, gzip, zstd1, zstd3
    compression: zstd1
  locality_to_default_cell:
    us: us1
  # data type must be organization or project_key
  data_type: organization
