[package]
name = "ingest-router"
version = "0.1.0"
edition = "2024"

[dependencies]
hyper = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
shared = { path = "../shared" }
http-body-util = { workspace = true }

[dev-dependencies]
serde_yaml = { workspace = true }
