[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
http = { workspace = true}
http-body-util = { workspace = true}
hyper = { workspace = true }
hyper-util = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
